site:
  title: Documentation
  start_page: home::index.adoc
  url: http:localhost:3000
  keys:
    docsearch_id: 'QK2EAH8GB0'
    docsearch_api: 'ef7bd9485eafbd75d6e8425949eda1f5'
    docsearch_index: 'prod_hazelcast_docs'
content:
  sources: 
  - url: .
    start_paths: [home,tutorials]
    branches: HEAD
  - url: https://github.com/hazelcast/hz-docs
    branches: [main, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/imdg-docs
    branches: [v/*]
    start_path: docs
  - url: https://github.com/hazelcast/imdg-docs
    branches: [archived-versions]
    start_paths: docs/*
  - url: https://github.com/hazelcast/management-center-docs
    branches: [main, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/management-center-docs
    branches: [archived-versions]
    start_paths: docs/*
  - url: https://github.com/hazelcast/cloud-docs
    branches: [main]
    start_path: docs
  - url: https://github.com/hazelcast/hazelcast-platform-operator-docs
    branches: [main, v/*]
    start_path: docs
  - url: https://github.com/hazelcast/turbine
    branches: [main]
    start_path: docs/content
  - url: https://github.com/hazelcast-guides/adoc-templates.git
    branches: antora-doc
  - url: https://github.com/hazelcast-guides/caching-springboot-jcache
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/hazelcast-embedded-springboot
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/springboot-hibernate
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/hibernate-jcache
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/istio
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/caching-micronaut
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/kubernetes-embedded
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/hazelcast-embedded-microprofile
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/hazelcast-client-quarkus
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/springboot-webfilter-session-replication
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/caching-springboot
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/ecs-embedded
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/striim-cdc
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/springboot-tomcat-session-replication
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/vmware-tanzu
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/terraform-quickstarts
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/kubernetes-external-client
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/active-directory-authentication
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/kubernetes-sidecar
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/kubernetes-hpa
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/kubernetes-ssl
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/kubernetes-wan
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/kubernetes
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/spring-session-hazelcast
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/ec2-cluster
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/linkerd
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/consul
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/openshift
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/nodejs-client-getting-started
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/go-client-getting-started
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/openfaas-hz-client
    branches: tutorials
    start_path: docs
  - url: https://github.com/hazelcast-guides/hazelcast-platform-operator-expose-externally
    branches: tutorials
    start_path: docs
ui: 
  bundle:
    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/download/v2.16-BETA/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-pagination: true@
    # Allows us to use UI macros. See https://docs.asciidoctor.org/asciidoc/latest/macros/ui-macros/
    page-experimental: true
    idprefix: ''
    idseparator: '-'
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    imdg-javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
    imdg-samples: https://github.com/hazelcast/hazelcast-code-samples
    imdg-core: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast
    imdg-docs: https://docs.hazelcast.org/docs/latest/manual/html-single/index.html
    imdg-ops-guide: https://hazelcast.com/resources/hazelcast-deployment-operations-guide/
    jet-docs: https://jet-start.sh/
    docs-archive: 'https://hazelcast.org/imdg/download/archives/'
  extensions:
    - ./lib/tabs-block.js
    - ./lib/swagger-ui-block-macro.js
